// AUTO-GENERATED by event-schema. Do not edit.
// Source: examples/ecommerce/event-schema.yaml

export type Money = { amount: number; currency: string };

export type AnalyticsEvents = {
  /**
   * A user viewed a product detail page.
   */
  product_viewed: {
    sku: string;
    price: Money;
    category?: string;
  };

  /**
   * A product was added to the cart.
   */
  add_to_cart: {
    sku: string;
    quantity: number;
    unit_price: Money;
  };

  /**
   * An order was successfully paid. The numerator of the storefront's
   * primary conversion funnel.
   */
  checkout_completed: {
    order_id: string;
    total: Money;
    items_count: number;
    first_purchase: boolean;
  };
};
