// AUTO-GENERATED by event-schema. Do not edit.
// Source: examples/minimal/event-schema.yaml

export type AnalyticsEvents = {
  /**
   * A user created an account.
   */
  signup: {
    method: "email" | "github" | "google";
  };
};
