// AUTO-GENERATED by event-schema. Do not edit.
// Source: examples/saas/event-schema.yaml

export type AnalyticsEvents = {
  /**
   * Account creation succeeded. Numerator of every funnel that ends at
   * "they are a real user".
   */
  signup_completed: {
    plan: "free" | "pro" | "growth";
    method: "email" | "github" | "google";
  };

  /**
   * Top-of-funnel engagement signal — which CTA earned the click.
   * Used for per-CTA conversion attribution and copy testing.
   */
  cta_click: {
    /**
     * Where on the page the CTA lives.
     * @example "hero_primary", "nav_signup", "final_cta_secondary"
     */
    location: string;
    /** The pathname (or external URL) the click navigates to. */
    destination: string;
  };

  /**
   * A core product feature was triggered.
   */
  feature_used: {
    feature: "export" | "share" | "comment" | "invite";
    via_keyboard_shortcut?: boolean;
  };

  /**
   * The user launched the app. No additional properties needed.
   */
  app_opened: Record<string, never>;
};
