import type { EventSchema, PropertyEntry } from "./load.js";

const MONEY_TYPE = `export type Money = { amount: number; currency: string };`;

interface GenerateOptions {
  typeName?: string;
  source?: string;
}

function buildHeader(opts: GenerateOptions): string {
  const sourceArg = opts.source || "<source>";
  return `// AUTO-GENERATED by event-schema. Do not edit.
// Source: ${sourceArg}
`;
}

function renderType(prop: PropertyEntry): string {
  switch (prop.type) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "enum":
      if (!prop.values || prop.values.length === 0) return "string";
      return prop.values.map((v) => JSON.stringify(v)).join(" | ");
    case "money":
      return "Money";
  }
}

function renderJsDoc(prop: PropertyEntry, indent: string): string {
  const lines: string[] = [];
  if (prop.description) lines.push(prop.description.trim());
  if (prop.examples && prop.examples.length > 0) {
    lines.push(`@example ${prop.examples.map((e) => JSON.stringify(e)).join(", ")}`);
  }
  if (lines.length === 0) return "";
  if (lines.length === 1) return `${indent}/** ${lines[0]} */\n`;
  return `${indent}/**\n${lines.map((l) => `${indent} * ${l}`).join("\n")}\n${indent} */\n`;
}

function renderEvent(properties: Record<string, PropertyEntry>): string {
  const keys = Object.keys(properties);
  if (keys.length === 0) return "Record<string, never>";

  const indent = "    ";
  const fields = keys.map((name) => {
    const prop = properties[name];
    const optional = prop.required === true ? "" : "?";
    const type = renderType(prop);
    const doc = renderJsDoc(prop, indent);
    return `${doc}${indent}${name}${optional}: ${type};`;
  });
  return `{\n${fields.join("\n")}\n  }`;
}

export function generateTypes(schema: EventSchema, options: GenerateOptions = {}): string {
  const typeName = options.typeName || "AnalyticsEvents";
  const eventNames = Object.keys(schema.events);
  const usesMoney = Object.values(schema.events).some((evt) =>
    Object.values(evt.properties).some((p) => p.type === "money"),
  );

  const eventLines = eventNames.map((name) => {
    const evt = schema.events[name];
    const intentDoc = evt.intent
      ? `  /**\n${evt.intent
          .trim()
          .split("\n")
          .map((l) => `   * ${l}`)
          .join("\n")}\n   */\n`
      : "";
    return `${intentDoc}  ${name}: ${renderEvent(evt.properties)};`;
  });

  const sections = [
    buildHeader(options),
    usesMoney ? MONEY_TYPE + "\n" : null,
    `export type ${typeName} = {\n${eventLines.join("\n\n")}\n};\n`,
  ].filter(Boolean);

  return sections.join("\n");
}
