// AUTO-GENERATED by event-schema. Do not edit.
// Source: examples/metrics/event-schema.yaml

export type AnalyticsEvents = {
  /**
   * Account creation succeeded. Numerator of every funnel.
   */
  signup_completed: {
    plan: "free" | "pro";
  };

  /**
   * Stripe checkout completed; user is now on a paid plan.
   */
  subscription_started: {
    plan: "pro";
  };
};

export type MetricName =
  | "daily_signups"
  | "weekly_pro_signups"
  | "weekly_signup_to_paid_cvr";

export type MetricSpec<M extends MetricName> = {
  /**
   * New signups per day. Top-of-funnel volume.
   */
  daily_signups: { type: "count"; grain: "day" };
  /**
   * Pro-tier signups per week. Distinguishes free trial from real intent.
   */
  weekly_pro_signups: { type: "count"; grain: "week" };
  /**
   * % of signups that converted to paid in the same week. Read as a
   * board-level lever, not a strict cohort retention metric.
   */
  weekly_signup_to_paid_cvr: { type: "ratio"; grain: "week" };
}[M];
